- htmlstuff/HTML/2803.html
- htmlstuff/HTML/3298.html
- htmlstuff/HTML/3318.html
- htmlstuff/HTML/3527.html
- htmlstuff/HTML/3561.html
- htmlstuff/HTML/3593.html
- htmlstuff/HTML/3599.html
- htmlstuff/HTML/3607.html
- htmlstuff/HTML/3627.html
- htmlstuff/HTML/3635.html
- htmlstuff/HTML/3694.html
- htmlstuff/HTML/3695.html
- htmlstuff/HTML/Script.js
- htmlstuff/HTML/old.txt
- htmlstuff/HTML/style1.css
- htmlstuff/HTML/te.html
- htmlstuff/HTML/test.html
- htmlstuff/Style1/2803.html
- htmlstuff/Style1/3298.html
- htmlstuff/Style1/3318.html
- htmlstuff/Style1/3527.html
- htmlstuff/Style1/3561.html
- htmlstuff/Style1/style1.css
the contents of html and bundle them with the style1CSS
> the contents of html and bundle them with the style1CSS

- Content/Scripts/Symbols/script.js
- Content/Styles/Symbols/Site.scss
Final version of the symbol style
> fix(symbols): fix the problem of the symbol icon

- Content/Scripts/SymbolFrames/script.js
- Content/Styles/SymbolFrames/Site.scss
final version of frame-indicator
> fix(frame-indicator): small indicator problem at table

- Content/Scripts/DividedFrames/script.js
- Content/Styles/Shared/Navbar.scss
add lines and fix frame problem
> fix(frame-divide): add divided lines

- Content/Scripts/Divided/script.js
- Content/Scripts/Toggle/script.js
- Content/Styles/Divided/Site.scss
- Content/Styles/DividedFrames/Site.scss
- Content/Styles/Toggle/Site.scss
- Views/Stacked/Item2803.cshtml
- Views/Stacked/Item3298.cshtml
- Views/Stacked/Item3318.cshtml
- Views/Stacked/Item3527.cshtml
- Views/Stacked/Item3561.cshtml
- Views/Stacked/Item3593.cshtml
- Views/Stacked/Item3599.cshtml
- Views/Stacked/Item3607.cshtml
- Views/Stacked/Item3627.cshtml
- Views/Stacked/Item3635.cshtml
- Views/Stacked/Item3694.cshtml
- Views/Stacked/Item3695.cshtml
- Change all fonts from sans serif to serif.
- Add hamburger icon.
- Add horizontal and vertical lines for styling.
- Reformat elements to accommodate new styles.
- Reformat tables to include serif font and dividing lines.
> Fix divided lines styling discrepancies

- Content/Scripts/Stack/script.js
- Content/Styles/Divided/Site.scss
- Content/Styles/DividedFrames/Site.scss
- Content/Styles/Frames/Site.scss
- Content/Styles/Stacked/Site.scss
- Content/Styles/SymbolFrames/Site.scss
- Content/Styles/Symbols/Site.scss
- Content/Styles/Toggle/Site.scss
- Views/Stacked/Item2803.cshtml
- Views/Stacked/Item3298.cshtml
- Views/Stacked/Item3318.cshtml
- Views/Stacked/Item3527.cshtml
- Views/Stacked/Item3561.cshtml
- Views/Stacked/Item3593.cshtml
- Views/Stacked/Item3599.cshtml
- Views/Stacked/Item3607.cshtml
- Views/Stacked/Item3627.cshtml
- Views/Stacked/Item3635.cshtml
- Views/Stacked/Item3694.cshtml
- Views/Stacked/Item3695.cshtml
finish the css style of stack. 
fix space problem of answer container
> fix(stack): style and space of answer container

- NavigationHelper.cs
- Views/Home/Index.cshtml
- Views/Shared/_Layout.cshtml
- wwwroot/css/site.css
separated items by grade and added home button for navigation
> feat(homepage): grade demarcation

- Content/Scripts/Toggle/script.js
Changed BOTH label in toggle style to show english and spanish translation
> fix(both label): change label to include both languages

- Content/Scripts/Divided/script.js
- Content/Styles/Divided/Site.scss
add question number in divided
> fix(divided): add question number

- NavigationHelper.cs
Changed order of items in the navigation list
> fix(item-order): change order of items

- Content/Scripts/SymbolFrames/script.js
- Content/Styles/Divided/Site.scss
- Content/Styles/SymbolFrames/Site.scss
- Content/Styles/Toggle/Site.scss
Fixes table spacing issues in the Toggle and Hybrid: Frames and Symbols formats.
> Fix/table-spacing Toggle and Hybrid: Frames and Symbols

- Views/Home/Index.cshtml
> fix(item-order): fixed grade 4 item order

- Content/Scripts/DividedFrames/script.js
- Content/Scripts/SymbolFrames/script.js
- Content/Styles/DividedFrames/Site.scss
- Fixes table spacing in columns and internally in the Toggle, Hybrid: Frames and Symbols, and Hybrid: Frames and Dividing Lines formats.
- Changes table font to serif in Hybrid: Frames and Symbols and Hybrid: Frames and Dividing Lines formats.
- Fixes dividing lines in tables in Hybrid: Frames and Dividing Lines format.
> Fix/table-spacing: Toggle, Hybrid: Frames and Symbols, & Hybrid: Frames and Dividing Lines

- Views/Home/Index.cshtml
> fix(item order): fixed item orders

- Content/Scripts/Toggle/script.js
switched order of toggle labels
> fix(sed-128): switched order of toggle labels

- Content/Styles/Divided/Site.scss
- Content/Styles/DividedFrames/Site.scss
> fix(sed-118): add lines between titles

- Content/Styles/Frames/Site.scss
- Content/Styles/SymbolFrames/Site.scss
> fix(sed-130): remove spacing inside frames

- Views/Shared/_Item2803.cshtml
- Views/Shared/_Item3694.cshtml
- Views/Shared/_Item3695.cshtml
This pull request fixes the formatting for the headings in items 2803, 3694 and 3695 across all formats.
> fix(indicators): fix headings for items 2803, 3694 and 3695

- Content/Scripts/SymbolFrames/script.js
- Content/Scripts/Toggle/script.js
- Content/Styles/Shared/Navbar.scss
- Content/Styles/Toggle/Site.scss
add missing indicators, add space between grid and prompt, add lines in toggle
> fix(all): add missing indicators, add space between grid and prompt, add

- Content/Styles/Divided/Site.scss
- Content/Styles/DividedFrames/Site.scss
- Content/Styles/Partials/_main.scss
- Content/Styles/Shared/Navbar.scss
- Content/Styles/Stack/Site.scss
- Content/Styles/SymbolFrames/Site.scss
- Content/Styles/Symbols/Site.scss
- Content/Styles/Toggle/Site.scss
- Views/Shared/_Layout.cshtml
- wwwroot/css/site.css
reduce nav icon size and change color
> fix(sed-131): reduce nav icon size and change color

- Views/Shared/_Layout.cshtml
Fixes code that was omitted by mistake through a merge.
> fix(toggle): fix logic for preserving language choice

- Content/Scripts/Divided/script.js
- Content/Scripts/DividedFrames/script.js
- Content/Styles/Divided/Site.scss
- Content/Styles/DividedFrames/Site.scss
- Unbolds dividing line in last row of table in item 2803.
- Removes extra dividing line in passage column of item 3695.
- Increases width of some columns and radio button answers to fix dividing line width.
> Fix Dividing Lines Spacing & Placement

- Content/Scripts/Divided/script.js
- Content/Scripts/DividedFrames/script.js
- Content/Scripts/Stacked/script.js
- Content/Scripts/SymbolFrames/script.js
- Content/Scripts/Symbols/script.js
- Content/Scripts/Toggle/script.js
- Content/Styles/Symbols/Site.scss
Fixes order of passage column content to:
- Spanish title
- English title
- Spanish content
- English content
on all formats, including the Both option in Toggle.
> Fix Order of Content

- Views/Shared/_Layout.cshtml
Home screen buttons had nav buttons in the footer that both led to the home screen. Removed them.
> fix(homescree-buttons): remove buttons from home screen

- Content/Scripts/Divided/script.js
- Content/Scripts/DividedFrames/script.js
- Content/Scripts/SymbolFrames/script.js
- Content/Scripts/Symbols/script.js
remove stacked formatting for titles
> fix(correct-titles): remove stacked formatting for titles

- README.md
- package-lock.json
> feat(docs): added docs
